# Generated by Django 5.1.4 on 2025-01-03 09:44

from django.db import migrations

from global_app.constants import (
    CUSTOMER,
    SYSTEM_ADMIN
)


def create_role(apps, schema_editor):

    Role = apps.get_model('system_management', 'Role')

    Role.objects.bulk_create([
        Role(role=SYSTEM_ADMIN),
        Role(role=CUSTOMER),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_role),
    ]
