# Generated by Django 5.1.4 on 2025-01-03 09:51

from django.db import migrations

from global_app.constants import (
    SOUTH_AFRICA
)


def create_country(apps, schema_editor):

    Country = apps.get_model('system_management', 'Country')
    Country.objects.create(
        country=SOUTH_AFRICA
    )


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0002_auto_20250103_1144'),
    ]

    operations = [
        migrations.RunPython(create_country)
    ]
