# Generated by Django 5.1.4 on 2025-01-03 10:00

from django.db import migrations

from global_app.constants import (
    MALE,
    FEMALE
)


def create_gender(apps, schema_editor):

    Gender = apps.get_model('system_management', 'Gender')
    Gender.objects.bulk_create([
        Gender(gender=MALE),
        Gender(gender=FEMALE)
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0004_auto_20250103_1155'),
    ]

    operations = [
        migrations.RunPython(create_gender),
    ]
