# Generated by Django 5.1.4 on 2025-01-03 10:03

from django.db import migrations

from global_app.constants import (
    OTHER,
    WHITE,
    ASIAN,
    INDIAN,
    AFRICAN,
    COLOURED,
)


def create_race(apps, schema_editor):
    Race = apps.get_model('system_management', 'Race')
    Race.objects.bulk_create([
        Race(race=OTHER),
        Race(race=WHITE),
        Race(race=ASIAN),
        Race(race=INDIAN),
        Race(race=AFRICAN),
        Race(race=COLOURED)
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0005_auto_20250103_1200'),
    ]

    operations = [
        migrations.RunPython(create_race),
    ]
