# Generated by Django 5.1.4 on 2025-01-19 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0006_auto_20250103_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=4)),
                ('street_address', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_management.country')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_management.gender')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_management.province')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_management.race')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='system_management.user')),
            ],
        ),
    ]
